version: '3.9'
services:

  foodgram_db:
    image: postgres:13.10
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgreesql/data
    env_file:
      - ./.env

  backend:
    image: nikitasalikov/foodgram_backend:latest
    restart: on-failure
    volumes:
      - static_foodgram:/app/static/
      - media_foodgram:/app/media/
    depends_on:
      - foodgram_db
    env_file:
      - ./.env

  frontend:
    image: nikitasalikov/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/infra/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/var/html/static/
      - media_foodgram:/var/html/media/
    depends_on:
      - backend

volumes:
  pg_data:
  static_foodgram:
  media_foodgram:
