version: '3.9'
services:

  foodgram_db:
    image: postgres:latest
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: nikitasalikov/foodgram_backend:latest
    restart: on-failure
    volumes:
      - static_foodgram:/app/backend_stastic/
      - media_foodgram:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - foodgram_db
    env_file:
      - ./.env

  frontend:
    image: nikitasalikov/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/infra/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_foodgram:/var/html/static/
      - media_foodgram:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

volumes:
  pg_data:
  static_foodgram:
  media_foodgram:
  redoc:
