# Generated by Django 3.2.3 on 2023-07-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
