# Generated by Django 3.2.3 on 2023-08-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
