# Generated by Django 3.2.3 on 2023-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(upload_to='foodgram/media', verbose_name='Изображение блюда'),
        ),
    ]
